### PR TITLE
Change tune_hyperparameters method name

### PR DESCRIPTION
**Pull request by sanskriti-s**
Changed to tune_hyperparameters_abc so it doesn't conflict with the name
of the fitness function

### CODE REVIEW

**Comment by tjkessler** [comment]
I'm not sure I understand - is this a bug fix for an incorrect method/function naming scheme?

This would also change the API, I'd like to avoid this unless it's absolutely necessary.

**Comment by hgromer** [comment]
I also don’t see why the distinction is necessary. Consumers won’t care what is being used to tune the hyper parameters.

**Comment by sanskriti-s** [comment]
They both had the same name. Wouldn't that risk calling it recursively?

**Comment by hgromer** [comment]
One belongs to the Server class (a method). So the call is made via Server.tune_hyperparameters(), the other is a function, and is called with tune_hyperparameters(). So they are different.

**Comment by sanskriti-s** [comment]
Okay.

**Pull request closed without merging**
